##ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
##FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu


FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.0